project_id              = ""
region                  = ""
agent_email             = ""
agent_email_password    = ""
agent_smtp_server       = ""
agent_smtp_port         = ""
email_receiver          = ""